<?php echo $this->render('common/header.phtml'); ?>
<script type="text/javascript" src="<?php echo $this->baseUrl?>/public/scripts/test.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl?>/public/scripts/dropdownmenu.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl?>/public/styles/dd.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl?>/public/styles/global.css" />
</head>
<?php echo $this->render('common/top.phtml'); ?>
<tr><td>tests</td>
</tr>
<?php echo $this->render('common/bottom.phtml'); ?>
<?php echo $this->render('common/footer.phtml'); ?>