	<tr>
		<td>
			<table width="100%" border="0" cellpadding="0" cellspacing="0" id="footer">
			  <tr>
					<td width="80%" align="center" style="padding:15px 0 0 0 ">
						<a href="http://www.tychio.com/About-Tychio/">About Us</a>
						<a href="http://www.tychio.com/Contact-Us.html?pf=2">Contact Us</a>
						<a href="http://www.tychio.com/Privacy.pdf">Privacy Policy</a>
						<a href="http://www.tychio.com/TermsOfUse.pdf">See our Terms of Service.</a>
						
						<!-- BEGIN Comm100 Live Chat Button Code -->
<!--<div><div id="comm100_LiveChatDiv"></div>-->
<a href="http://www.comm100.com/livechat/" onclick="comm100_Chat();return false;" target="_blank" title = "Live Chat Live Help Software for Website">
<img id="comm100_ButtonImage" src="http://chatserver.comm100.com/BBS.aspx?siteId=28452&planId=519" border="0px" width=0 alt="Live Chat Live Help Software for Website" />Help</a>
<script src="http://chatserver.comm100.com/js/LiveChat.js?siteId=28452&planId=519"type="text/javascript"></script>
<!-- <div id="comm100_track" style="z-index:99;"><span style="font-size:10px; font-family:Arial, Helvetica, sans-serif;color:#555"></span></div></div> -->
<!-- End Comm100 Live Chat Button Code -->

						
						
						<!--<a href="<?php echo $this->baseUrl?>/termsofuse.pdf">See our Terms of Service.</a>-->   Copyright &copy; 2009 Tychio Inc.
					</td>					
				</tr>
			</table>
		</td>
	</tr>
</table>