<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><?php echo $this->escape($this->title); ?></title>
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl?>/public/styles/global.css" />
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl?>/public/styles/style.css" />
    <script type="text/javascript" src="<?php echo $this->baseUrl?>/public/scripts/jquery-1.4.2.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl?>/public/scripts/uncompressed.jquery.dd.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl?>/public/scripts/jquery.json-2.2.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl?>/public/scripts/json.js"></script>    