<body class="main">
<table width="1000" height="100%" border="0" align="center" cellpadding="0" cellspacing="0">
	<tr>
		<td height="154" align="left" valign="top">
			<table width="1000" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="315" height="154" align="left" valign="top">
						<a href="http://www.tychio.com"><img src="<?php echo $this->baseUrl?>/public/images/logo.jpg" width="294" height="154" alt=""></a>
					</td>
					<td align="left" valign="top">
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="right"><img src="<?php echo $this->baseUrl?>/public/images/spacer.gif" alt="" width="1" height="7"></td>
							<td></td>
						  </tr>
						  <tr>
							<td height="46" align="right" valign="top"></td>
							<td></td>
						  </tr>
						  <tr>
							<td align="right"><?php echo $this->stepbystep ?></td>
							<td align="right"><?php echo $this->litle_logo ?></td>
						  </tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
