<?php echo $this->render('common/header.phtml'); ?>
<script type="text/javascript" src="<?php echo $this->baseUrl?>/public/scripts/dropdownmenu.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl?>/public/styles/dd.css" />
<script type="text/javascript">
      function validateForm()
      {
          var re = /^\w+([\.-]?\w+)*@(((([a-z0-9]{2,})|([a-z0-9][-][a-z0-9]+))[\.][a-z0-9])|([a-z0-9]+[-]?))+[a-z0-9]+\.([a-z]{2}|(com|net|org|edu|int|mil|gov|arpa|biz|aero|name|coop|info|pro|museum))$/i;
          var str = $("#email").attr("value");
          if($("#fname").attr("value").length == 0)
            alert(" \"First Name\" is required.");
          else
          if($("#lname").attr("value").length == 0)
            alert(" \"Last Name\" is required.");
          else
          if($("#cname").attr("value").length == 0)
            alert(" \"Company / Organization\" is required.");
          else
          if($("#email").attr("value").length == 0)
            alert(" \"Email Address\" is required.");
          else
          if($("#email").attr("value").length != 0 && !re.test(eval('str')))
          {
               alert(" \"Email Address\" is not valid.");
          }
          else
          if($("#number").attr("value").length == 0)
            alert(" \"Contact Number\" is required.");
          else
          {
                var requestObject = new Object();
                requestObject.fname = $("#fname").attr("value");
                requestObject.lname = $("#lname").attr("value");
                requestObject.cname = $("#cname").attr("value");
                requestObject.email = $("#email").attr("value");
                requestObject.number = $("#number").attr("value");
                requestObject.checkBox = $("#opt_in_id").attr("checked");

                var jsonRequest = JSON.stringify(requestObject);
                var url = './registration/registration';
                $.ajax({
                   type: "get",
                   url: url,
                   dataType : "json",
                   data: "request="+jsonRequest
                   ,error: location.href= "<?php echo $this->baseUrl?>/score?xsession_id=<?php echo (($this->person_id)*712)?>"
                });
          }
      }
  </script>
</head>
<?php echo $this->render('common/top.phtml'); ?>
<tr>
	<td >
		<table width="1000" border="0" cellspacing="0" cellpadding="0" >
			<tr  align='center'>
				<td valign="top">
					<table width="600px" border="0" cellspacing="10" cellpadding="10"  class="myFont">
                        <tr style="height: 40px;">
							<td>                                								
							</td>
						</tr>
						<tr align="left">
							<td>
                                Please tell us about yourself:								
							</td>
						</tr>
						  <tr align="left">
							  <td  width="200px">
								  First Name:
							  </td>
							  <td width="200px">
								  <input id="fname" name="fname" class="pl-inputxt" type="text" />&nbsp;*
							  </td>
						</tr>
						<tr align="left">
							  <td>
								  Last Name:
							  </td>
							  <td>
								  <input id="lname" name="lname" class="pl-inputxt" type="text" />&nbsp;*
							  </td>
						</tr>
						<tr align="left">
							  <td>
								  Company / Organization:
							  </td>
							  <td>
								  <input id="cname" name="cname" class="pl-inputxt" type="text" />&nbsp;*
							  </td>
						</tr>
						<tr align="left">
							  <td>
								  Email Address:
							  </td>
							  <td>
								  <input id="email" name="email" class="pl-inputxt" type="text" />&nbsp;*
							  </td>
						</tr>
						<tr align="left">
							  <td>
								  Contact Number:
							  </td>
							  <td>
								  <input id="number" name="number" class="pl-inputxt" type="text" />&nbsp;*
							  </td>
						</tr>
						<tr align="right">
							<td colspan=2>
								<input type="button" id="btnNext" onClick="validateForm();" class="showmybiiq"/>
								
							</td>
						</tr>
					</table>
				</td>
		<!-- 		<td align="left" valign="center">
                    <div id="progressBar" class="progressBar progressBar100"  style="margin-top:100px;">
                        <div class='cell'>
                            <div class="interestOnProgressBar">
                                100%
                            </div>
                        </div>
                    </div>
				</td> -->
			</tr>
            <tr align='center'>
                <td >
                     <input style="margin-top: 20px; margin-bottom:20px;" type="checkbox" <?php echo $this->checked ?>  id="opt_in_id" value="a2">
                     <label for="opt_in_id">Keep me informed on how I can improve my BIIQ scores using tools, techniques and processes.</label>
                </td>
            </tr>
		</table>
	</td>
</tr>
<?php echo $this->render('common/bottom.phtml'); ?>
<?php echo $this->render('common/footer.phtml'); ?>